name: FE CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - uses: actions/checkout@v3

      # 2. Create .env.prod (Next.js buildìš©)
      - name: Create .env.production
        working-directory: ./frontend
        run: |
          cat > .env.production << 'EOF'
          NODE_ENV=production
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_SOCKET_URL=${{ secrets.NEXT_PUBLIC_SOCKET_URL }}
          
          STATIC_URL=${{ secrets.STATIC_URL }}
          LAMBDA_UPLOAD_URL=${{ secrets.LAMBDA_UPLOAD_URL }}
          EOF

      # 3. Docker Hub Login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build FE Docker Image
      - name: Build FE Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest \
            ./frontend

      # 5. Push FE Docker Image
      - name: Push FE Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      # 6. SSH to EC2 and deploy
      - name: Deploy via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            docker-compose pull frontend
            docker-compose up -d frontend
